name: Daily Trade Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * 1-5'  # Runs every weekday at 14:00 UTC (9:00 EST)

jobs:
  run-tradebot:
    runs-on: ubuntu-latest

    env:
      ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
      ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
      ALPACA_BASE_URL: ${{ secrets.ALPACA_BASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

      - name: Run Alpaca Bot
        run: python main.py
